In [19]:
import pandas as pd,re,requests,time
from bs4 import BeautifulSoup
import datetime
import psycopg2
from sqlalchemy import create_engine
from sqlalchemy.sql import text
from notifier import sendErrorMsg

#returns the daily_id from dailytable
def getDailyIdFromDailyTable(engine,record_df):
    #get Cursor
    record_df.to_sql('daliytable', engine, if_exists='append',index=False)
    #alter the sequence of the id i.e. restarting from 1
    #ALTER SEQUENCE <tablename>_<id>_seq RESTART WITH 1
    with engine.connect() as connection:
        result_set=connection.execute("SELECT id from daliytable order by id desc limit 1;")
        for i in result_set:
            return(i['id'])

#this function gets portal id from websiteportal 
def getPortalIdFromWebsitePortal(engine):
    with engine.connect() as connection:
        result_set= connection.execute("SELECT id from websiteportal where portal = 'Indeed' limit 1;")
        for i in result_set:
            return(i['id'])

#inseting into recprds table
def insertRecordsToRecords(engine,data_matrix):
    data_matrix.to_sql('records',engine,if_exists='append',index=False)
    print("inserting success")

In [36]:
if __name__=='__main__':    
    dat=datetime.datetime.today()
    start=0
    lengthOfRecord=0
    numberOfJobs=0
    dataFrame=pd.DataFrame()
    df=pd.DataFrame()
    date=[]
    company=[]
    location=[]
    summary=[]
    posted_date=[]
    posted_day=[]
    posted_links=[]
    companyUrl=[]
    designation=[]
    countries=['Canada','Singapore','USA','UK','Ireland','Bahrain','Oman','Qatar']
    for job in ['jaspersoft','Talend']:
        appendurl='/jobs?as_and='+str(job)+'&as_phr="Talend"&as_any=&as_not=&as_ttl=&as_cmp=&jt=all&st=&salary=&radius=25&l=&fromage=any&limit=50&start=%s&sort=date&psf=advsrch'
        urls=['https://ca.indeed.com','https://www.indeed.com.sg','https://www.indeed.com','https://www.indeed.co.uk',\
              'https://ie.indeed.com','https://bh.indeed.com','https://om.indeed.com','https://qa.indeed.com']
        try:
            urls=[url1,url2,url3,url4,url5,url6,url7,url8]
            for url,country in zip(urls,countries):
                counter=0
                while lengthOfRecord <= numberOfJobs:
                    urll= ((url+appendurl)%start)
                    soup= BeautifulSoup(requests.get(urll).text,'lxml')
                    numberOfHits= soup.find("div",id="searchCount").text
                    numberOfHits= [re.sub(r'[^A-Za-z0-9]+', '', x) for x in numberOfHits.strip().split(" ")]
                    if len(numberOfHits) == 6:
                        numberOfJobs=int(numberOfHits[5])
                    if len(numberOfHits) == 5:
                        numberOfJobs=int(numberOfHits[3])
                    print("Number of Jobs: ",numberOfJobs,"record count: ",start," Job: ",job,"country: ",country)
                    result= soup.find_all("div",class_="row result clickcard".split())
                    lengthOfRecord= lengthOfRecord+len(result)
                    if lengthOfRecord <= numberOfJobs:
                        total=numberOfJobs
                        for firstLink in result:
                            try:
                                links= firstLink.find('a',{"class":"turnstileLink"})
                                date.append(dat.strftime('%d-%m-%Y'))
                                company.append(firstLink.find('span',{"class":"company"}).text.strip())
                                
                                location.append(firstLink.find('span',{"class":"location"}).text.strip())
                                
                                summary.append(firstLink.find('span',{"class":"summary"}).text.strip())
                                
                                companyl= firstLink.find('span',{"class":"company"}).findChildren()
                                #print(firstLink.find('span',{"class":"date"}))
                                try:
                                    l=firstLink.find('span',{"class":"date"}).text
                                except Exception as e:
                                    print(e)
                                posted_day.append(l)
                                dt=None
                                
                                li=re.sub(r'[^0-9A-Z]','',l)
                                
                                #print(li,li.find('hour',0,len('hour')))
                                try:
                                    if li.isalpha():
                                        dt=dat.date()
                                    else:
                                        dt=(dat-datetime.timedelta(days=int(li))).date()
                                except ValueError as e:
                                    print("i am out")
                                    print(e)
                               
                                posted_date.append(dt)
                                posted_links.append(url+links['href'])
                                designation.append(links['title'])
                                
                                if (len(companyl) != 0):
                                    for i in companyl:
                                        try:
                                            companyUrl.append(url+i['href'])
                                        except KeyError as e:
                                            print("KeyError: Not a Problem",e)
                                else:
                                    companyUrl.append("NULL")
                            except Exception as e:
                                break;
                                print(e)
                                
                    else:
                        break
                    counter +=1
                    start=start+50
                print(len(company),len(location),len(summary),len(posted_date),len(posted_day),len(posted_links),len(companyUrl))
                df['posted_date']=posted_date
                df['posted_day']=posted_day
                df['posted_links']=posted_links
                df['designation']=designation
                df['company_name']=company
                df['companyurl']=companyUrl
                df['location']= [ loc+' '+ job for loc in location]
                df['summary']=summary 
                print("DF shape and number of Jobs: ",df.shape,numberOfJobs)

                dataFrame=dataFrame.append(df)   
                start=0      #setting again 0 to new searches
                lengthOfRecord=0
                numberOfJobs=0
                df=pd.DataFrame()
                numberOfJobs=0
                date=[]
                company=[]
                location=[]
                summary=[]
                posted_date=[]
                posted_day=[]
                posted_links=[]
                companyUrl=[]
                designation=[]
        except Exception as e:
            print(e,"asdfasdf asdf",url)
            

dataFrame.to_csv("C:/Datasets/JobData/daily_indeed_"+str(dat.strftime('%d_%m_%Y'))+".csv")
#framing the table and crawled date for DB
record=[(dat.date(),'daily_indeed_'+str(dat.strftime('%d_%m_%Y')+".csv"))]
record_df=pd.DataFrame(record,columns=['crawled_date','filename'])

engine = create_engine('postgresql+psycopg2://postgres:postgres@localhost:5432/job_data')
daily_id=getDailyIdFromDailyTable(engine,record_df)
portal_id=getPortalIdFromWebsitePortal(engine)
dataMatrix=dataFrame
dataMatrix['day_id']=daily_id
dataMatrix['portal_id']=portal_id
dataMatrix['posted_date']=dataMatrix['posted_date'].apply(lambda d : datetime.datetime.strptime(d,"%Y-%m-%d").date() if isinstance(d, str) else d)
insertRecordsToRecords(engine,dataMatrix)

Number of Jobs:  4 record count:  0  Job:  jaspersoft country:  Canada
0 0 0 0 0 0 0
DF shape and number of Jobs:  (0, 8) 4
'NoneType' object has no attribute 'text' asdfasdf asdf https://www.indeed.com.sg
Number of Jobs:  106 record count:  0  Job:  Talend country:  Canada
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
Number of Jobs:  106 record count:  50  Job:  Talend country:  Canada
53 53 53 53 53 53 53
DF shape and number of Jobs:  (53, 8) 106
Number of Jobs:  38 record count:  0  Job:  Talend country:  Singapore
Number of Jobs:  38 record count:  50  Job:  Talend country:  Singapore
0 0 0 0 0 0 0
DF shape and number of Jobs:  (0, 8) 38
Number of Jobs:  816 record count:  0  Job:  Talend country:  USA
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
Number of Jobs:  816 record count:  50  Job:  Talend country:  USA
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
KeyError: Not a Problem 'href'
'NoneType' object has no attribute 'text'
Number of Jobs:  816 record count:  100  Job:  Talend country:  USA
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
Number of Jobs:  816 record count:  150  Job:  Talend country:  USA
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
KeyError: Not a Problem 'href'
KeyError: Not a Problem 'href'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
Number of Jobs:  816 record count:  200  Job:  Talend country:  USA
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
KeyError: Not a Problem 'href'
KeyError: Not a Problem 'href'
'NoneType' object has no attribute 'text'
Number of Jobs:  816 record count:  250  Job:  Talend country:  USA
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
KeyError: Not a Problem 'href'
KeyError: Not a Problem 'href'
KeyError: Not a Problem 'href'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
Number of Jobs:  816 record count:  300  Job:  Talend country:  USA
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
KeyError: Not a Problem 'href'
KeyError: Not a Problem 'href'
KeyError: Not a Problem 'href'
'NoneType' object has no attribute 'text'
Number of Jobs:  816 record count:  350  Job:  Talend country:  USA
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
KeyError: Not a Problem 'href'
KeyError: Not a Problem 'href'
KeyError: Not a Problem 'href'
KeyError: Not a Problem 'href'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
Number of Jobs:  816 record count:  400  Job:  Talend country:  USA
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
KeyError: Not a Problem 'href'
KeyError: Not a Problem 'href'
KeyError: Not a Problem 'href'
KeyError: Not a Problem 'href'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
Number of Jobs:  816 record count:  450  Job:  Talend country:  USA
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
KeyError: Not a Problem 'href'
KeyError: Not a Problem 'href'
KeyError: Not a Problem 'href'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
Number of Jobs:  816 record count:  500  Job:  Talend country:  USA
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
KeyError: Not a Problem 'href'
KeyError: Not a Problem 'href'
'NoneType' object has no attribute 'text'
Number of Jobs:  816 record count:  550  Job:  Talend country:  USA
'NoneType' object has no attribute 'text'
KeyError: Not a Problem 'href'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
Number of Jobs:  816 record count:  600  Job:  Talend country:  USA
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
KeyError: Not a Problem 'href'
KeyError: Not a Problem 'href'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
Number of Jobs:  816 record count:  650  Job:  Talend country:  USA
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
Number of Jobs:  816 record count:  700  Job:  Talend country:  USA
'NoneType' object has no attribute 'text'
KeyError: Not a Problem 'href'
KeyError: Not a Problem 'href'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
'NoneType' object has no attribute 'text'
Number of Jobs:  816 record count:  750  Job:  Talend country:  USA
784 784 784 784 784 784 784
DF shape and number of Jobs:  (784, 8) 816
Number of Jobs:  187 record count:  0  Job:  Talend country:  UK
KeyError: Not a Problem 'href'
KeyError: Not a Problem 'href'
KeyError: Not a Problem 'href'
Number of Jobs:  187 record count:  50  Job:  Talend country:  UK
KeyError: Not a Problem 'href'
KeyError: Not a Problem 'href'
Number of Jobs:  187 record count:  100  Job:  Talend country:  UK
KeyError: Not a Problem 'href'
KeyError: Not a Problem 'href'
Number of Jobs:  187 record count:  150  Job:  Talend country:  UK
Number of Jobs:  187 record count:  200  Job:  Talend country:  UK
166 166 166 166 166 166 166
DF shape and number of Jobs:  (166, 8) 187
Number of Jobs:  11 record count:  0  Job:  Talend country:  Ireland
Number of Jobs:  11 record count:  50  Job:  Talend country:  Ireland
11 11 11 11 11 11 11
DF shape and number of Jobs:  (11, 8) 11
'NoneType' object has no attribute 'text' asdfasdf asdf https://bh.indeed.com
    posted_date    posted_day  \
0    2018-03-07         Today
1    2018-03-07         Today
2    2018-03-07         Today
3    2018-03-06     1 day ago
4    2018-03-06     1 day ago
5    2018-03-06     1 day ago
6    2018-03-06     1 day ago
7    2018-03-06     1 day ago
8    2018-03-03    4 days ago
9    2018-03-03    4 days ago
10   2018-03-02    5 days ago
11   2018-03-02    5 days ago
12   2018-03-02    5 days ago
13   2018-03-02    5 days ago
14   2018-03-02    5 days ago
15   2018-03-01    6 days ago
16   2018-03-01    6 days ago
17   2018-03-01    6 days ago
18   2018-02-26    9 days ago
19   2018-02-26    9 days ago
20   2018-02-27    8 days ago
21   2018-02-27    8 days ago
22   2018-02-23   12 days ago
23   2018-02-24   11 days ago
24   2018-02-24   11 days ago
25   2018-02-27    8 days ago
26   2018-02-22   13 days ago
27   2018-02-22   13 days ago
28   2018-02-15   20 days ago
29   2018-02-16   19 days ago
..          ...           ...
147  2018-02-05  30+ days ago
148  2018-02-05  30+ days ago
149  2018-02-05  30+ days ago
150  2018-02-05  30+ days ago
151  2018-02-05  30+ days ago
152  2018-02-05  30+ days ago
153  2018-02-05  30+ days ago
154  2018-02-05  30+ days ago
155  2018-02-05  30+ days ago
156  2018-02-05  30+ days ago
157  2018-02-05  30+ days ago
158  2018-02-05  30+ days ago
159  2018-02-05  30+ days ago
160  2018-02-05  30+ days ago
161  2018-02-05  30+ days ago
162  2018-02-05  30+ days ago
163  2018-02-05  30+ days ago
164  2018-02-05  30+ days ago
165  2018-02-05  30+ days ago
0    2018-03-01    6 days ago
1    2018-02-28    7 days ago
2    2018-02-28    7 days ago
3    2018-02-28    7 days ago
4    2018-02-07   28 days ago
5    2018-02-05  30+ days ago
6    2018-02-05  30+ days ago
7    2018-02-05  30+ days ago
8    2018-02-05  30+ days ago
9    2018-02-05  30+ days ago
10   2018-02-05  30+ days ago

                                          posted_links  \
0    https://ca.indeed.com/rc/clk?jk=2f402ee7be777c...
1    https://ca.indeed.com/company/ShoreWise-Consul...
2    https://ca.indeed.com/company/ShoreWise-Consul...
3    https://ca.indeed.com/rc/clk?jk=1aea4c29255947...
4    https://ca.indeed.com/rc/clk?jk=f55e998566591a...
5    https://ca.indeed.com/rc/clk?jk=15b63831358244...
6    https://ca.indeed.com/rc/clk?jk=8d88a94ab51505...
7    https://ca.indeed.com/rc/clk?jk=f1558aa7fec9b2...
8    https://ca.indeed.com/rc/clk?jk=683baa6598704e...
9    https://ca.indeed.com/rc/clk?jk=93dfe59ed1f466...
10   https://ca.indeed.com/rc/clk?jk=601d7e789a4009...
11   https://ca.indeed.com/rc/clk?jk=0bee243d1fb967...
12   https://ca.indeed.com/rc/clk?jk=bdfe83ab3f3a60...
13   https://ca.indeed.com/rc/clk?jk=cbc973751959b9...
14   https://ca.indeed.com/rc/clk?jk=9421e16ee8fc47...
15   https://ca.indeed.com/company/Infotek-Consulti...
16   https://ca.indeed.com/rc/clk?jk=fe76b835bd1cda...
17   https://ca.indeed.com/rc/clk?jk=bbd2bb2d0c520c...
18   https://ca.indeed.com/company/ERP&Si/jobs/Big-...
19   https://ca.indeed.com/company/ERP&Si/jobs/Seni...
20   https://ca.indeed.com/rc/clk?jk=5e8340ce88e5d4...
21   https://ca.indeed.com/company/FlexGroup/jobs/A...
22   https://ca.indeed.com/rc/clk?jk=c743d861e3970d...
23   https://ca.indeed.com/rc/clk?jk=eef8894ea95ad9...
24   https://ca.indeed.com/rc/clk?jk=2abe0196c4fae1...
25   https://ca.indeed.com/rc/clk?jk=a81dfb9b72e530...
26   https://ca.indeed.com/rc/clk?jk=1b87e6c5afbbe1...
27   https://ca.indeed.com/rc/clk?jk=2d50b544ca6d5c...
28   https://ca.indeed.com/rc/clk?jk=3c02dc545d484c...
29   https://ca.indeed.com/rc/clk?jk=07dde5eb3726a0...
..                                                 ...
147  https://www.indeed.co.uk/rc/clk?jk=92e125c1074...
148  https://www.indeed.co.uk/rc/clk?jk=f50b930f526...
149  https://www.indeed.co.uk/rc/clk?jk=24184ece9e9...
150  https://www.indeed.co.uk/rc/clk?jk=73fc8c15384...
151  https://www.indeed.co.uk/rc/clk?jk=c199d05e94c...
152  https://www.indeed.co.uk/rc/clk?jk=fb118677f32...
153  https://www.indeed.co.uk/rc/clk?jk=4448fe84672...
154  https://www.indeed.co.uk/rc/clk?jk=d0313b4eb21...
155  https://www.indeed.co.uk/rc/clk?jk=91a9177f602...
156  https://www.indeed.co.uk/rc/clk?jk=7078e09bc03...
157  https://www.indeed.co.uk/rc/clk?jk=c8b30e9ef1f...
158  https://www.indeed.co.uk/rc/clk?jk=620cbc22d8f...
159  https://www.indeed.co.uk/rc/clk?jk=cab0c420636...
160  https://www.indeed.co.uk/rc/clk?jk=775c2945fef...
161  https://www.indeed.co.uk/company/NeosAlpha/job...
162  https://www.indeed.co.uk/rc/clk?jk=0b74f95b90b...
163  https://www.indeed.co.uk/rc/clk?jk=613e1461690...
164  https://www.indeed.co.uk/rc/clk?jk=b30196a53b9...
165  https://www.indeed.co.uk/rc/clk?jk=a01209dd5a6...
0    https://ie.indeed.com/rc/clk?jk=88163539fcf1bd...
1    https://ie.indeed.com/rc/clk?jk=0677636a47259f...
2    https://ie.indeed.com/company/sonra/jobs/Big-D...
3    https://ie.indeed.com/rc/clk?jk=fac27db7c79829...
4    https://ie.indeed.com/rc/clk?jk=72b270f8a890d4...
5    https://ie.indeed.com/rc/clk?jk=3268a3a0198d4f...
6    https://ie.indeed.com/rc/clk?jk=05b6b70b3f775b...
7    https://ie.indeed.com/rc/clk?jk=a4574a5a05f074...
8    https://ie.indeed.com/rc/clk?jk=4b883ab0a2aaff...
9    https://ie.indeed.com/rc/clk?jk=2f44363ff31385...
10   https://ie.indeed.com/rc/clk?jk=68bf115a8d941a...

                                           designation  \
0    Senior IT Data Analyst (Big Data ETL Developer...
1                                              QA Lead
2                                        Senior QA ETL
3                                      Hadoop Engineer
4                       Développeur, plateforme Hadoop
5       IT Data Specialist (Data Architect & Dev Lead)
6                                 Programmer Analyst I
7                            Senior IT Data Specialist
8                                          Développeur
9                                Solutions IT Designer
10                             Data Insights Developer
11                                     Développeur ETL
12                   ISL 24R - Data Insights Developer
13                                 Analyste de données
14                                        Data Analyst
15                         Senior ETL Talend Developer
16          DATA Engineer – Downtown Vancouver (AD_DA)
17   Cloud Integration Specialist - Long-term Contract
18                                  Big Data Developer
19                           Senior Big Data Developer
20                      Dynamics GP Support Specialist
21                   ANALYSTE PROGAMMEUR WEB - AP-1802
22                                Talend ETL Developer
23                           Senior Software Architect
24                             Architecte de logiciels
25                        Java ETL application support
26                                 Technical Architect
27                     Cloud Systems Engineer - 248937
28                        Senior ETL/DB Developer Lead
29                       Big Data/Cloud Engineer (AWS)
..                                                 ...
147                           Talend Big Data Engineer
148                         Data Engineer (Data Tribe)
149         Visual Intelligence & Analytics Consultant
150                               Lead Content Analyst
151    Business Analyst - Data Quality, Data Modelling
152              VP of Data Engineering & Architecture
153  BI & Data Developers -SQL Server, learn new Da...
154                                       Data Analyst
155  Senior ETL Developer - Data Warehouse, Talend,...
156           Pre-Sales Consultant - MDM, Data Quality
157                            Java Developer (Retail)
158              Data Analyst (part-time or full-time)
159                     Senior Site Engagement Manager
160  Senior Software Engineer – Business Intelligen...
161                              Integration Developer
162                                      Data Engineer
163                                 Lead Data Engineer
164                                      BI Specialist
165                Specialist GSS Technical Consultant
0                            Senior Database Developer
1      Consultant Digital Engineer - Data Supply Chain
2                 Big Data, ETL, Data Warehouse Intern
3                                        BI Consultant
4                        Data Governance Administrator
5                                        Java Engineer
6                                     BI/ETL Test Lead
7                          Visual Analytics Consultant
8        Data Engineer – Big Data - Analytics Delivery
9      Big Data Solution Architect -Analytics Delivery
10                                       Data Engineer

                           company_name  \
0                               TD Bank
1              ShoreWise Consulting Inc
2              ShoreWise Consulting Inc
3                                  Bell
4                                  Bell
5                               TD Bank
6        University of British Columbia
7                               TD Bank
8                            Fondaction
9                               TD Bank
10        BC Liquor Distribution Branch
11                      Altitude Sports
12                    BC Public Service
13                              TD Bank
14                              TD Bank
15          Infotek Consulting Services
16                 Corporate Recruiters
17           Ignite Technical Resources
18                               ERP&Si
19                               ERP&Si
20              Trudell Medical Limited
21                            FlexGroup
22               Annex Consulting Group
23                     Thinking Capital
24                     Thinking Capital
25                   ProVision Staffing
26            MatchBox Consulting Group
27                               Procom
28                                 Citi
29                              Interac
..                                  ...
147                           Cognizant
148                Sky Betting & Gaming
149                           Accenture
150               Electrocomponents plc
151                     kdr Recruitment
152               Electrocomponents plc
153                     McGregor Boyall
154                  Datatech Analytics
155                     kdr Recruitment
156                     kdr Recruitment
157              esure Services Limited
158                            Elsevier
159                        QuintilesIMS
160                            Elsevier
161                           NeosAlpha
162                              Kainos
163                              Kainos
164                             Camelot
165                     Hitachi Vantara
0                             TechStorm
1                             Accenture
2           Sonra Intelligence Limited.
3    Tech Data Client Solutions Ireland
4          Mitsubishi UFJ Fund Services
5                 Reperio Human Capital
6                                Sogeti
7                             Accenture
8                             Accenture
9                             Accenture
10                Reperio Human Capital

                                            companyurl  \
0                    https://ca.indeed.com/cmp/Td-Bank
1                                                 NULL
2                                                 NULL
3                       https://ca.indeed.com/cmp/Bell
4                       https://ca.indeed.com/cmp/Bell
5                    https://ca.indeed.com/cmp/Td-Bank
6    https://ca.indeed.com/cmp/University-of-Britis...
7                    https://ca.indeed.com/cmp/Td-Bank
8                 https://ca.indeed.com/cmp/Fondaction
9                    https://ca.indeed.com/cmp/Td-Bank
10   https://ca.indeed.com/cmp/Bc-Liquor-Distributi...
11           https://ca.indeed.com/cmp/Altitude-Sports
12   https://ca.indeed.com/cmp/Bc-Public-Service-Ag...
13                   https://ca.indeed.com/cmp/Td-Bank
14                   https://ca.indeed.com/cmp/Td-Bank
15   https://ca.indeed.com/cmp/Infotek-Consulting-S...
16      https://ca.indeed.com/cmp/Corporate-Recruiters
17                                                NULL
18                                                NULL
19                                                NULL
20                                                NULL
21                                                NULL
22                                                NULL
23          https://ca.indeed.com/cmp/Thinking-Capital
24          https://ca.indeed.com/cmp/Thinking-Capital
25                 https://ca.indeed.com/cmp/Provision
26                                                NULL
27                    https://ca.indeed.com/cmp/Procom
28                      https://ca.indeed.com/cmp/Citi
29                   https://ca.indeed.com/cmp/Interac
..                                                 ...
147  https://www.indeed.co.uk/cmp/Cognizant-Technol...
148  https://www.indeed.co.uk/cmp/Sky-Betting-&-Gaming
149             https://www.indeed.co.uk/cmp/Accenture
150  https://www.indeed.co.uk/cmp/Electrocomponents...
151                                               NULL
152  https://www.indeed.co.uk/cmp/Electrocomponents...
153                                               NULL
154                                               NULL
155                                               NULL
156                                               NULL
157  https://www.indeed.co.uk/cmp/Esure-Services-Li...